[package]
name = "blazar_winapi_sys"
version = "1.0.0-dev.1"
authors = ["Mickaël Malécot <mickael.malecot@gmail.com>"]
edition = "2018"
description = "Windows API raw FFI bindings"
license = "MIT/Apache-2.0"
repository = "https://github.com/mmalecot/blazar"
